### ISSUE TITLE
Display search field when there are enough items to select

### ISSUE THREAD

**Issue by niom** [arendjr/selectivity#100]
Would be nice if there would be a configuration where you could give a treshold value when to display search field. 

e.g. $().selectivity({displaySearchFieldTreshold:50}), this would display search field when there are 50 or more items to choose from.

**Comment by arendjr** [comment]
How would you envision this? Currently you can already do something like this `$el.selectivity({ items: items, showSearchInputInDropdown: items.length > 50 })`. Of course this only works if you have a static list of items, and doesn't work with a dynamic query function. But then again, how should it work in combination with a dynamic query function? Because in that case the amount of results is typically not known upfront...

**Comment by niom** [comment]
would that work when you apply selectivity to traditional select element, those are pretty static. 

Not really gave a thought about dynamical loading. Would it be too difficult to just add the search field to the dropdown and when the threshold is achieved we could make the search field visible.

**Comment by arendjr** [comment]
For the traditional elements I would suggest doing the following: `$select.selectivity({ showSearchInputInDropdown: $select.find('option').length > 50 })`

For your second suggestion I guess it would be possible, but honestly I don't think it would result in a good user experience. In case the number of results is large, the search box should've been visible from the start but then will only appear once the threshold is reached. For dynamic situations, if you want to stay safe, I think it's better to just always show the search input.
