### ISSUE TITLE
select multiple & event change

### ISSUE THREAD

**Issue by Pascal76** [arendjr/selectivity#138]
Hi

when I want to get SELECT content, I got "undefined"
Is it a bug ?

`$('#mything').selectivity().on("change", function(e){
        var total =  e.value;
        alert(total);
    });`
The same for "added" or "removed"
If I try selectivity("value") it gives me the old content (before the change) !

**Comment by arendjr** [comment]
Does it work when you do the following?

    $('#mything').selectivity();
    $('#mything').on("change", function(e){ var total = e.value; alert(total); });

I admit there is some confusing behavior when you make use of the traditional plugin for converting an existing `<select>` input to a Selectivity instance. The original `<select>` will be hidden and a `<div>` will be created to which the Selectivity instance is attached. The problem is the jQuery container you used for selecting the `<select>` doesn't know that, so you're probably adding the event listener to the wrong DOM node.

I'm hoping to improve this behavior in the next API version.

**Comment by Pascal76** [comment]
still "undefined"

**Comment by arendjr** [comment]
Hm, that is unexpected... And with `$('#mything:not(select)')`?

**Comment by Pascal76** [comment]
sorry arendjr, I moved to select2 to not loose more time for my project.

**Comment by arendjr** [comment]
No hard feelings :)
