### ISSUE TITLE
Backdrop missing / clicking outside dropdown doesn't close

### ISSUE THREAD

**Issue by tjfroll** [arendjr/selectivity#168]
Can't tell if this is an intended change or not (I see no mention in the release notes), but in >= 3.0, there is no more `selectivity-backdrop`, which I believe was previously responsible for capturing clicks outside of a dropdown to trigger a close.

This is pretty critical functionality; without it, UX suffers greatly.

**Comment by tjfroll** [comment]
On further investigation, this is at least partially due to our implementation of `positionDropdown`, which we started overwriting after 1.1 since dropdowns are positioned inline (and none of the dropdowns in our app desire that behavior). Ours are appended to the body and positioned absolutely. This appears to interfere with how the close detection now operates.

Any suggestions for how to proceed? Only option I see at the moment is to manually recreate the backdrop and implement our own close listener.

**Comment by arendjr** [comment]
It was an intentional change, yes. The background has a downside which is that any click outside of the component is intercepted... which is nice for recognizing when to close the dropdown, but not so nice when the user tries to intentionally click another component and is bumped when the first click doesn't appear to do anything (besides closing the dropdown, which he may or may not have already forgotten about by then).

But you're right the new approach requires the dropdown to be added inline to the DOM where the rest of the component is mounted.

If you really cannot accept the dropdowns being positioned inline, I'm afraid bringing back the backdrop would be best way forward for you. If you want I would be willing to accept a PR that reintroduces the backdrop, even if that module probably wouldn't be enabled in the default build. But I can imagine having it upstream would be easier for you and might be advantageous for others as well. Of course such a PR should be accompanied by good tests as well :)

I will close this issue here as I don't think there's much more I can do for you now...
