### ISSUE TITLE
allowClear on single select 

### ISSUE THREAD

**Issue by killermouse** [arendjr/selectivity#211]
Hi,
when I have a allowClear on a single select that have more than one row by item, the clear button "X" does not work!
I send a attached to view the case.
![select](https://user-images.githubusercontent.com/19575806/31380989-02d0d6be-adab-11e7-8774-5e92e1c69d00.png)

Best regards

**Comment by dmarchuk** [comment]
@killermouse I think the problem is that the element with selected item is actually covering the clear button (X). Quick fix would be to just add this to your styles:
```css
.selectivity-single-selected-item-remove {
  position: relative;
  z-index: 1;
}
```

@arendjr I've made a [pull request](https://github.com/arendjr/selectivity/pull/213) with this hotfix. The problem can be seen for example here: https://jsfiddle.net/dmarchuk/9Ltevh10/2/. If you select the item in the select and then try to clear it with "X", it won't work. Here is an example of the same select but with the fix applied: https://jsfiddle.net/dmarchuk/9Ltevh10/1/

**Comment by killermouse** [comment]
@dmarchuk thank you.
Problem resolved.

Best regards

**Comment by arendjr** [comment]
Thanks guys!
