### ISSUE TITLE
API Methods throws error

### ISSUE THREAD

**Issue by dmpol18** [arendjr/selectivity#26]
On API example page
$('#example-1').selectivity('remove') throws an error Unknown method: remove
as well as some other methods

**Comment by arendjr** [comment]
I think this is intentional. The remove() method only exists on multiple-value inputs. You'll see `$('#example-2').selectivity('remove')` doesn't throw an error.

The documentation has comment *(multiple-value inputs only)* for both the add and remove methods. So I believe it's safe to close this issue.

**Comment by dmpol18** [comment]
Oh, sorry, I thought It should remove the option from the list. Thanks.
