### ISSUE TITLE
Compliance with standard web form elements

### ISSUE THREAD

**Issue by msx2** [arendjr/selectivity#29]
Currently when you define a selectivity input out of standard HTML's:
* `select`, this element gets replaced completely with selectivity input
* `input`, the logic works, but everything is appended into the `input` tag, creating something like `<input>...</input>`

What about support for standard web forms? If I try to turn `select` into selectivity input, it will end up with removing the select field completely from the form. That shouldn't be the case.

The similar situation is `multiple: true` defined on the `input`. The logic seems to operate, but nothing happens, and field is removed from the form as well.

`Select2` has this not-really-so-great approach of hiding those standard elements and injecting/updating values within once selection is made, but that's actually pretty awesome as it allows users to prettify the select boxes and not modify anything else about the code for it to work as it should (and did).

**Comment by arendjr** [comment]
The behavior you see is implemented in the selectivity-traditional module. If you don't use this module, you should always initialize Selectivity with an empty `<div>` which will act as a container for the templates. What the traditional module adds is being able to use a `<select>` element which is used to initialize many of Selectivity's constructor options, after which indeed it is replaced by a `<div>` and the initialization continues as normal.

Personally, I use a build without the traditional module in my projects, simply because those projects are single-page applications and initialization through pure JavaScript is easier and more efficient than first rendering a template with all the options, and then converting that back to an options object through the traditional module.

Now, from a technical design perspective, I had some goals that I considered important. One of them was to make Selectivity simple and light-weight. Another was to make it very easy to use custom templates. Both these goals are served very well by simply starting with an empty `<div>` and just rendering our own template in there. Considering how much code it takes in Select2, for example, to synchronize the hidden `<select>` element with their own state, I felt there's a lof of efficiency to be gained from not going that route. With Selectivity the model is now very simple, we have our own API that people can use, and there is zero support for querying the original elements, because they are simply removed from the DOM.

The traditional module was created as a compromise to people who have existing `<select>` boxes they want to prettify. While some improvement to that module might be possible, I think it would be very difficult to try and maintain references to the original `<select>` elements next to the templated content. If it can be achieved relatively easily, I wouldn't be against it, but I wouldn't want to sacrifice the simplicity of the core model to achieve it either.

PS.: Using an `<input>` element for initializing Selectivity with the traditional module is not even supported according to our docs (see the intro here: https://arendjr.github.io/selectivity/#api). I know Select2 does have some support for `<input>` elements, but I never quite understood the point of it, given that there is no `type` value that maps to a select box in HTML. Both single- and multiple-value select boxes should be represented with `<select>` elements.

**Comment by msx2** [comment]
For single page applications that operate strictly on front-end layer, yes, I agree that pure JS solution is what makes it awesome. There's no doubt about it.

The problem however appears once you try a traditional approach, to use it in the application that consists of many pages, and many forms. Then the approach of fields and values initialized with pure JavaScript that way is a bit painful. It's easier and more convenient to render the page, and then bind events on existing page elements. E.g. in Ruby on Rails you may send forms via AJAX by simply adding `data-remote="true"` to the form (if Unobtrusive JavaScript is used, and https://github.com/rails/jquery-ujs) and bind events in JavaScript to handle the response, e.g. `ajax:success`.

I think that adding a `<select>` element to the structure (with name, id etc... from the original DOM element) and then injecting values from selectivity inputs wouldn't be much of a deal for traditional module. It could be done a bit better than in `select2` - i.e. injecting options that were selected, and only those options. No need for tons of unnecessary options that slow down the page. I think it might be relatively easy especially considering that there is already a `span data-item-id="xxx"` being injected into the container. :)

The only additional code that would need to be added is creating a mirror object hidden within selectivity container (to hold the created `select`), and the line responsible for adding/removing options, but that code already exists for handling `span`s.

What do you think?

**Comment by msx2** [comment]
As for using `<input>` to initialize component - well, it's not supported but possible. And produces invalid HTML structure. This could be disabled using `alert()` to inform users that something is wrong... :)

**Comment by kevin-brown** [comment]
> I know Select2 does have some support for <input> elements, but I never quite understood the point of it, given that there is no type value that maps to a select box in HTML.

`<input type="text" />` is only supported in Select2 4.0 for backwards compatibility with older versions.

The only time I would ever recommend it is for an autocomplete, definitely not for a select box.

> This could be disabled using alert() to inform users that something is wrong... :)

`console.warn` is great for giving warnings (or errors) for developers.

**Comment by msx2** [comment]
> `console.warn` is great for giving warnings (or errors) for developers.

I agree for the `console.warn`, or even `console.error`. `alert()` was just a mere example. The method used for this purpose does not matter at the moment though - it's only a wishful thinking for future release. :wink:

**Comment by arendjr** [comment]
> I think that adding a `<select>` element to the structure (with name, id etc... from the original DOM element) and then injecting values from selectivity inputs wouldn't be much of a deal for traditional module. It could be done a bit better than in `select2` - i.e. injecting options that were selected, and only those options. No need for tons of unnecessary options that slow down the page. I think it might be relatively easy especially considering that there is already a `span data-item-id="xxx"` being injected into the container. :)

> The only additional code that would need to be added is creating a mirror object hidden within selectivity container (to hold the created `select`), and the line responsible for adding/removing options, but that code already exists for handling `span`s.

Well, I guess it is at least worth to check if it is as easy as you say it is :)
