### ISSUE TITLE
Form submission

### ISSUE THREAD

**Issue by nlemoine** [arendjr/selectivity#88]
Hi, 

Sorry for the dumb question. To be clear, unlike using the traditionnal module with a `select` tag, values from a selectivity field have to be set (in a hidden field `input`) by custom code binding the change event?

**Comment by arendjr** [comment]
Uh, good question. This specific functionality was made by @msx2, so hopefully he can tell a bit more about it :)

What I know is that the functionality for making Selectivity fields submittable with a form is implemented in the traditional module, but honestly I'm not sure myself if it requires initialization from a `select` tag or not.

**Comment by msx2** [comment]
Hi @nlemoine. Well, it took me a while to get here. Sorry for that.

If I understand the issue correctly, you want to be able to send data through the form without using tranditional module, right? If so, yes, you need a custom binding with hidden input on your side. Though this is precisely the issue that traditional module tries to solve, so you don't have to manipulate DOM yourself and create any additional bindings. Since we are dealing with a dropdown select library its primary use case is to replace default `select` tag so it has to be initialized using one - there is no proper support for `input` element as of today (at least not that I'm aware of).

I hope this answers your question. :)

Is there any reason in particular why you don't want a `select` tag and would rather go with `input` instead?

**Comment by nlemoine** [comment]
Hi @msx2, 

Yes, that was my question and you totally answered it. Thanks for your feedback ;)

> Is there any reason in particular why you don't want a `select` tag and would rather go with `input` instead?

Yes, I have a form with multiple `select` fields (20). Each one contains a quite big amount of items (600+), The item list is the same for each field. For performance reasons, I'd rather populate these `select` fields with a json object. Using the `select` option in my case is slow because the page gets quite heavy with 600x20 options and the script has to parse and render all these options for each field. 

I know I can add custom bindings to fill an hidden `input` with selected values. But I was actually making the assumption that this kind of plugin was mostly used in a form context and therefore wondering if there was an easy built in way to get these values back (without any additional work). 

A no issue was posted about this topic, I guess that's a pretty specific problem. So I'll go for custom binding ;)
