### ISSUE TITLE
Add method for single value inputs?

### ISSUE THREAD

**Issue by loriensleafs** [arendjr/selectivity#99]
Hi,

there's an add method, but it seems to be for multi value inputs only.  Is there no method for adding a new value to a dropdown that only allows a single value to be selected?

If there isn't is there a plan to add this functionality, and is there a workaround for this?

Thanks!

**Comment by arendjr** [comment]
Hi there, what exactly do you think the add() method does? add() and remove() are indeed only for multi-selection inputs, because they add and remove items from the *selection*, something which I only think makes sense when you can select more than one item. But if you want you want to add something to the list of items from which to choose, you can achieve that by just re-setting the *items* option.

Cheers!

**Comment by loriensleafs** [comment]
awwww, got it.  Definitely misunderstood their purpose, thanks for the clarification!

**Comment by arendjr** [comment]
No problem :)
